Models/Customers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Vidly1.Models
{
    public class Customers
    {
        public int Id { get; set; }
        public String Name { get; set; }
        


    }
       
}

Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly1.Models
{
    public class Movie
    {

        public int Id { get; set; }
        public String Name { get; set; }
    }
}

ViewModels/DetailsCustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly1.Models;

namespace Vidly1.ViewModels
{
    public class DetailsCustomerViewModel
    {

        public List<Customers>Customers { get; set; }
        
             
    }   
}



ViewModels/DetailsMovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly1.Models;

namespace Vidly1.ViewModels
{
    public class DetailsMovieViewModel
    {
        public List<Movie> Movie { get; set; }
    }
}

Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly1.Models;
using Vidly1.ViewModels;

namespace Vidly1.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers


        public ActionResult Index()
        {
                
            var customers = new List<Customers>

            {

                new Customers { Id = 1, Name = "John Smith" },
                new Customers { Id = 2, Name = "Mary Williams" }
            };


            var viewModel = new DetailsCustomerViewModel
            {
                Customers = customers


            };

            return View(viewModel);
        }



        public ActionResult Details()
        {


            var customers = new List<Customers>
            {

            new Customers { Id = 1, Name = "John Smith" },
            new Customers { Id = 2, Name = "Mary Williams" }

           
            };
            

            if (!customers.Any())
                return HttpNotFound();

            var viewModel = new DetailsCustomerViewModel
        
            {
                Customers = customers

            };
            

            return View(viewModel);



    }

}
}


Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidly1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly1.Models;
using Vidly1.ViewModels;

namespace Vidly1.Controllers
{
    public class MoviesController : Controller
    {
        // GET: Movies
        public ActionResult Index()
        {

            var movie = new List<Movie>
            {
                new Movie { Id = 1, Name = "Shrek" },
                new Movie { Id = 2, Name = "Wall-e" }

            };


            var viewModel = new DetailsMovieViewModel
            {
                Movie = movie


            };
            return View(viewModel);

        }


        public ActionResult Details()
        {


            var movie = new List<Movie>
            {

            new Movie { Id = 1, Name = "Shrek" },
            new Movie { Id = 2, Name = "Wall-e" }


            };


            if (!movie.Any())
                return HttpNotFound();

            var viewModel = new DetailsMovieViewModel

            {
                Movie = movie

            };


            return View(viewModel);


        }



    }
}

Views/Customers/Details.cshtml
@model Vidly1.ViewModels.DetailsCustomerViewModel



@{
    ViewBag.Title = "customers.Name";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


 @foreach (var customers in Model.Customers)
    {


        if (Model.Customers.Count > 0)
        {

               <h1>@customers.Name</h1>

        }

        else
        {
         <p>@customers</p>
        }


 }















Views/Customers/Index.cshtml
@model Vidly1.ViewModels.DetailsCustomerViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers</h2>


@if (Model.Customers.Count == 0)
{
    <text>There are no customers.</text>

}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Customer</th>

            </tr>
        </thead>

        @foreach (var customer in Model.Customers)
        {

            <tbody>
                <tr>
                    <td>@Html.ActionLink(customer.Name, "Details", "Customers", new { id = customer.Id }, null)</td>

                </tr>
            </tbody>



        }
    </table>



}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Movies/Details.cshtml
@model Vidly1.ViewModels.DetailsMovieViewModel

@{
    ViewBag.Title = "@movie.Name";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@foreach (var movie in Model.Movie)
{


    if (Model.Movie.Count > 0)
    {

        <h1>@movie.Name</h1>

    }
        
    else
    {
        <p>@movie</p>
    }


}


Views/Movies/Index.cshtml
@model Vidly1.ViewModels.DetailsMovieViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h2>Movies</h2>


@if (Model.Movie.Count == 0)
{
    <text>There are no movies.</text>

}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Movie</th>

            </tr>
        </thead>

        @foreach (var movie in Model.Movie)
        {

            <tbody>
                <tr>
                    <td>@Html.ActionLink(movie.Name, "Details", "Movies", new { id = movie.Id }, null)</td>

                </tr>
            </tbody>



        }
    </table>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
               
                <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
            </ul>
        </div>
    </div>
</div>
